name: rspl_network_manager
description: A Flutter plugin that simplifies networking with configurable logging, token persistence, mock API support, automatic token refresh, connectivity checks, and proxy configuration.
version: 2.0.0
homepage: https://github.com/rishabhsoftwarepvtltd/FlutterNetworkManager
repository: https://github.com/rishabhsoftwarepvtltd/FlutterNetworkManager
issue_tracker: https://github.com/rishabhsoftwarepvtltd/FlutterNetworkManager/issues
license: LicenseRef-Rishabh-Software-Non-Commercial-1.0

environment:
  sdk: ^3.9.0

platforms:
  android:
  ios:
  macos:
  web:

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.10.0
  flutter_secure_storage: ^10.3.1
  dio_smart_retry: ^7.0.1
  connectivity_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4